# Generated by Django 4.1.7 on 2023-03-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_blacklistusers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistusers',
            name='number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blacklistusers',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
